In [1]:
# like C++ #include, Python can import modules
import numpy as np    # now we can refer to numpy simply as "np"
#from numpy import *  # imports one single thing, into global namespace, as if we did "using namespace numpy"

In [1]:
import seaborn as sb

In [2]:
help(sb)

Help on package seaborn:

NAME
    seaborn - # Import seaborn objects

PACKAGE CONTENTS
    _core
    _decorators
    _docstrings
    _statistics
    _testing
    algorithms
    apionly
    axisgrid
    categorical
    cm
    colors (package)
    conftest
    distributions
    external (package)
    linearmodels
    matrix
    miscplot
    palettes
    rcmod
    regression
    relational
    tests (package)
    timeseries
    utils
    widgets

DATA
    crayons = {'Almond': '#EFDECD', 'Antique Brass': '#CD9575', 'Apricot':...
    xkcd_rgb = {'acid green': '#8ffe09', 'adobe': '#bd6c48', 'algae': '#54...

VERSION
    0.11.2

FILE
    /home/jtanderson/.local/lib/python3.8/site-packages/seaborn/__init__.py




In [2]:
# python has a dir(.) method to see all the methods/attributes on objects

In [3]:
# main data structure in numpy is the array/ndarray
x = [1,2,3,4]

In [6]:
x2 = np.array(x)

In [7]:
print(x)

[1, 2, 3, 4]


In [8]:
print(x2)

[1 2 3 4]


In [9]:
type(x2)

numpy.ndarray

In [11]:
x = np.array([1,2,3,4])
y = np.array([4,5,6,7])

In [12]:
print(x + y)

[ 5  7  9 11]


In [13]:
x

array([1, 2, 3, 4])

In [14]:
list(x)

[1, 2, 3, 4]

In [15]:
list(x) + list(y)

[1, 2, 3, 4, 4, 5, 6, 7]

In [16]:
np.sqrt(x)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [17]:
x * 10

array([10, 20, 30, 40])

In [28]:
A = np.array([
    [2,3,4],
    [3,1,0],
    [0,1,1]
])

x = np.array([1,3,4])

In [29]:
A * x  # will broadcast the 1x3 into a 3x3 by vertically copying,
       # then does element-wise multiplication

array([[ 2,  9, 16],
       [ 3,  3,  0],
       [ 0,  3,  4]])

In [30]:
# want the actual matrix-vector product: use the operator @
A @ x

array([27,  6,  7])

In [31]:
A.shape

(3, 3)

In [32]:
x.shape

(3,)

In [33]:
x = np.array([[1,3,4]])

In [34]:
x.shape

(1, 3)

In [35]:
A*x

array([[ 2,  9, 16],
       [ 3,  3,  0],
       [ 0,  3,  4]])

In [37]:
A @ x # will not work now because x is actually 1x3

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 3)